### ISSUE TITLE
Postprocess bcbio

### ISSUE THREAD

**Issue by kokyriakidis** [umccr/umccrise#33]
Hello @vladsaveliev ! Can you provide a reference yaml file with all the parameters you use in Bcbio piplepine which gives the best available vcf file for input in ummcrise?

Also, in workflow.md, I see that you also use SAGE which I think is not supported in bcbio. Do you have a modified bcbio pipeline? If yes, can I have access to it?

**Comment by vladsaveliev** [comment]
Hi @kokyriakidis,

We support a tumor-normal whole genome variant calling, with the ensemble or strelka2-only somatic and germline calls, and manta as a structural variant caller. Here is an example of a bcbio yaml file: https://github.com/umccr/umccrise_test_data/blob/master/data/bcbio_test_project/config/2018-11-30T1125_Avner_WGS-merged.yaml

Regarding SAGE, we run it in postprocessing, so we don't need bcbio to run it for us. SAGE is pretty fast because it's run just on a predefined set of hotspots, so it fits right in a post-processing pipeline. Same story for a copy number caller we use: it's [PURPLE](https://github.com/hartwigmedical/hmftools/tree/master/purity-ploidy-estimator), which we run in postprocessing as well.

Hope it helps!

**Comment by kokyriakidis** [comment]
Thank you so much for your answer! Some follow up questions:

1) Do I need this file? Where can I find it? Is there one for Hg38?:
‘’’
coverage: /g/data3/gx8/extras/umccr_cancer_genes.v1.GRCh37.bed
‘’’

2) Can I use ummcrise on only Germline data? If yes, can I add deepvariant on on germline variant caller list?

3) In a tumor-normal case, do I specify both germline and somatic in the variant caller list, as you do in the test yaml you send me?
‘’’
 variantcaller:
      germline: [vardict, strelka2, gatk-haplotype]
      somatic: [vardict, strelka2, mutect2]
‘’’
