### ISSUE TITLE
CONDA_PREFIX set to `//miniconda/envs/` in Dockerfile because root user has no HOME

### ISSUE THREAD

**Issue by alexiswl** [umccr/umccrise#67]
Getting a lot of errors in the snakemake script etc.

```
File path //miniconda/envs/umccrise/lib/python3.7/site-packages/ngs_utils/reference_data/key_genes/predispose_genes.hg38.transcript.bed contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
```

This is likely from the CONDA_PREFIX and PATH env vars being set in https://github.com/umccr/umccrise/blob/master/Dockerfile#L41-L42

In this case, $HOME is set to `/` because the user is not set.  

I would first scrap the $HOME prefix of those lines in the Dockerfile and 
then create a umccrise user and group and chown of /miniconda to said user.

Then set `USER` in the Dockerfile

**Comment by brainstorm** [comment]
Related to https://github.com/umccr/umccrise/issues/36 ?

**Comment by ohofmann** [comment]
We'll have to rebuild this eventually anyway. Might as well do this now while we have a working install in prod...

**Comment by scwatts** [comment]
Agree this makes sense to do. A minor complication is that the AWS wrapper script creates a directory on the root path at runtime and installs aws-cli to `/usr/local/`:
- https://github.com/umccr/infrastructure/blob/master/cdk/apps/umccrise/assets/umccrise-wrapper.sh#L77
- https://github.com/umccr/infrastructure/blob/master/cdk/apps/umccrise/assets/umccrise-wrapper.sh#L82

To allow us to run the Docker image with a non-root user, in the Dockerfile we could:
- create the `/work/` directory with correct user permissions
- install aws-cli

If there are no objections, I'll make these changes and open the necessary PRs.

**Comment by scwatts** [comment]
Hm, the `/work/` directory is actually external storage that mounts with `root:root` ownership in the Docker container. I can't see an obvious way to change mount ownership within containers when executing as a non-root user.

For reference the `/work/` directory is derived by:
- defining an EBS device in the launch template to attach to the instance ([here](https://github.com/umccr/infrastructure/blob/master/cdk/apps/umccrise/stacks/batch.py#L135)) 
- formatting the EBS device and mounting at `/mnt/` on the **Batch instance** ([here](https://github.com/umccr/infrastructure/blob/master/cdk/apps/umccrise/assets/batch-user-data.sh#L39-L40))
- setting `/mnt/` as a Docker volume named `work` ([here](https://github.com/umccr/infrastructure/blob/master/cdk/apps/umccrise/stacks/batch.py#L295))
- mounting the `work` Docker volume at `/work/` in the **Docker container** ([here](https://github.com/umccr/infrastructure/blob/master/cdk/apps/umccrise/stacks/batch.py#L277))

Any thoughts on the Docker side of this issue @alexiswl?

If changing mount ownership in a container with non-root isn't possible an alternative could be to update the Umccrise stack so that the attached EBS storage is intrinsically available to the Docker image rather than manually formatting and mounting. I've done similar for the AGHA GDR stack [here](https://github.com/umccr/agha-data-validation-pipeline/blob/development/stacks/agha_stack.py#L97). Though there may be some reason I don't understand it hasn't been done this way... Not sure this is all worth the effort - could be easier just to leave root as the executing user at that point.

**Comment by scwatts** [comment]
Apologies for the duplicate commit - I didn't rebase prior to pushing to the fork; the first is now orphaned and can be ignored.

Please see https://github.com/umccr/umccrise/pull/68.
